### PR TITLE
fix: fix rendering of Decorated Pot

### PR DESCRIPTION
**Pull request by Wolf2323**
This is currently a draft that adds the `decorated_pot`.

more blocks from #122 will be added

### CODE REVIEW

**Comment by zardoy** [comment]
@Wolf2323 I still can't push commits to this PR (most probably because you don't have push access to branch you're opening from or because you can't grant write access to other people like me)

**Comment by zardoy** [comment]
Anyway, I tried to apply the texture in a naive way (as I described before) and it didn't work. Do you know do uv values apply against the target texture in the range from 0-16 (where 16 is 100%)? I have all the tiles that have a constant height of 16 (since all blocks are 16x16) since I generate a single texture called an atlas for more effective loading & caching on GPU. I need to think of a way to make it compatible with other entity texture :thinking:
image

**Comment by Wolf2323** [comment]
I will look into this tomorrow, for today i am out of time

**Comment by zardoy** [comment]
@Wolf2323 I almost figured it out, however since its a multi-version project, please let's change the blockStates / blockModels path format so it's in the folder with the version. For example if support for some block was added in 1.20 it is inside of `1.20/blockStates/blockName.json` and so on. I will handle the code so you can just add json files for new blocks

image

**Comment by zardoy** [comment]
@Wolf2323 still can't get your changes pushed here: https://github.com/zardoy/prismarine-web-client/pull/new/decorated-pot

**Comment by Wolf2323** [comment]
I dont get what you mean now. But for the rest of the day, i will now work on this topic

**Comment by Wolf2323** [comment]
@zardoy you now have permissions on the repo

**Comment by zardoy** [comment]
forgot to update the test as we added supported for deocrateded_pot 🎉

**Pull request merged**
